# version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: make start
    ports:
      - "8000:8000"
    volumes:
      - ".:/app"
      - "/tmp:/tmp"
    depends_on:
      - db
    env_file:
      - '.env.docker'


  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: page_analyzer
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql:ro
      

volumes:
  pgdata: